# Generated by Django 3.0.6 on 2020-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bj_app', '0003_auto_20200930_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bj_item',
            name='bj_title',
            field=models.CharField(max_length=256),
        ),
    ]
