# Generated by Django 3.0.6 on 2020-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bj_app', '0004_auto_20200930_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bj_item',
            name='bj_reportingTime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bj_item',
            name='bj_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
