# Generated by Django 3.0.6 on 2020-10-01 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bj_app', '0005_auto_20200930_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bj_item',
            options={'ordering': ('-published', '-pk')},
        ),
        migrations.RemoveField(
            model_name='bj_item',
            name='bj_reportingTime',
        ),
        migrations.RemoveField(
            model_name='bj_item',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bj_item',
            name='author',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bj_item',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bj_item',
            name='bj_content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bj_item',
            name='bj_title',
            field=models.CharField(max_length=100),
        ),
    ]
